language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t syedhasnain0099/docker-react .

script:
  - docker run -e CI=true syedhasnain0099/docker-react npm test -- --coverage
