sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t syedhasnain0099/docker-react .

script:
  - docker run syedhasnain0099/docker-react npm run test -- --coverage
